import type { Booking } from './types';

export function generateMockBookings(): Booking[] {
  return [
    {
      id: 'UB-STO-1001',
      status: 'in_storage',
      createdAt: '2026-04-15T10:30:00Z',
      studentName: 'Sarah Chen',
      email: 'schen@buffalo.edu',
      phone: '(716) 555-0101',
      housingType: 'dorm',
      dormName: 'Ellicott Complex',
      roomNumber: '412',
      floor: 4,
      hasElevator: true,
      boxCount: 8,
      furnitureItems: [
        { type: 'Mini Fridge', price: 69.99, quantity: 1 },
      ],
      cardboardBoxesRequested: 6,
      boxDeliveryDate: '2026-05-04',
      pickupDate: '2026-05-12',
      pickupTimeSlot: '9am-12pm',
      fallDeliveryDate: '2026-08-24',
      fallDeliveryScheduledLater: false,
      fallDeliveryHousingType: 'dorm',
      hasInsurance: true,
      insurancePhotosSent: true,
      totalPrice: 178.92,
      depositAmount: 35.79,
      depositPaid: true,
      depositPaymentMethod: 'venmo',
      balancePaid: true,
      balancePaymentMethod: 'venmo',
    },
    {
      id: 'UB-STO-1002',
      status: 'deposit_paid',
      createdAt: '2026-04-20T14:15:00Z',
      studentName: 'Marcus Johnson',
      email: 'mjohnson@buffalo.edu',
      phone: '(716) 555-0102',
      housingType: 'dorm',
      dormName: 'Governors Complex',
      roomNumber: '208',
      floor: 2,
      hasElevator: false,
      boxCount: 5,
      furnitureItems: [],
      cardboardBoxesRequested: 5,
      boxDeliveryDate: '2026-05-05',
      pickupDate: '2026-05-14',
      pickupTimeSlot: '12pm-3pm',
      fallDeliveryDate: '',
      fallDeliveryScheduledLater: true,
      fallDeliveryHousingType: 'dorm',
      hasInsurance: false,
      insurancePhotosSent: false,
      totalPrice: 74.95,
      depositAmount: 15.0,
      depositPaid: true,
      depositPaymentMethod: 'zelle',
      balancePaid: false,
    },
    {
      id: 'UB-STO-1003',
      status: 'booked',
      createdAt: '2026-04-25T09:00:00Z',
      studentName: 'Emily Rodriguez',
      email: 'erodriguez@buffalo.edu',
      phone: '(716) 555-0103',
      housingType: 'off-campus',
      address: '123 Main St, Apt 4B, Buffalo, NY 14214',
      floor: 1,
      hasElevator: false,
      boxCount: 12,
      furnitureItems: [
        { type: 'TV', price: 59.99, quantity: 1 },
        { type: 'Items Larger than Standard Box', price: 79.99, quantity: 1 },
      ],
      cardboardBoxesRequested: 5,
      boxDeliveryDate: '2026-05-06',
      pickupDate: '2026-05-15',
      pickupTimeSlot: '3pm-6pm',
      fallDeliveryDate: '2026-08-25',
      fallDeliveryScheduledLater: false,
      fallDeliveryHousingType: 'off-campus',
      hasInsurance: true,
      insurancePhotosSent: false,
      totalPrice: 208.88,
      depositAmount: 41.78,
      depositPaid: false,
      balancePaid: false,
    },
    {
      id: 'UB-STO-1004',
      status: 'boxes_delivered',
      createdAt: '2026-04-22T16:45:00Z',
      studentName: 'James Park',
      email: 'jpark@buffalo.edu',
      phone: '(716) 555-0104',
      housingType: 'dorm',
      dormName: 'Greiner Hall',
      roomNumber: '615',
      floor: 6,
      hasElevator: true,
      boxCount: 6,
      furnitureItems: [
        { type: 'TV', price: 59.99, quantity: 2 },
      ],
      cardboardBoxesRequested: 4,
      boxDeliveryDate: '2026-05-04',
      pickupDate: '2026-05-13',
      pickupTimeSlot: '9am-12pm',
      fallDeliveryDate: '2026-08-26',
      fallDeliveryScheduledLater: false,
      fallDeliveryHousingType: 'dorm',
      hasInsurance: false,
      insurancePhotosSent: false,
      totalPrice: 89.94,
      depositAmount: 18.0,
      depositPaid: true,
      depositPaymentMethod: 'stripe',
      balancePaid: false,
    },
    {
      id: 'UB-STO-1005',
      status: 'picked_up',
      createdAt: '2026-04-10T11:20:00Z',
      studentName: 'Aisha Patel',
      email: 'apatel@buffalo.edu',
      phone: '(716) 555-0105',
      housingType: 'dorm',
      dormName: 'Flint Village',
      roomNumber: '103',
      floor: 1,
      hasElevator: false,
      boxCount: 10,
      furnitureItems: [
        { type: 'Items Larger than Standard Box', price: 79.99, quantity: 1 },
      ],
      cardboardBoxesRequested: 6,
      boxDeliveryDate: '2026-05-05',
      pickupDate: '2026-05-11',
      pickupTimeSlot: '12pm-3pm',
      fallDeliveryDate: '2026-08-24',
      fallDeliveryScheduledLater: false,
      fallDeliveryHousingType: 'dorm',
      hasInsurance: true,
      insurancePhotosSent: true,
      totalPrice: 178.9,
      depositAmount: 35.78,
      depositPaid: true,
      depositPaymentMethod: 'venmo',
      balancePaid: true,
      balancePaymentMethod: 'venmo',
    },
    {
      id: 'UB-STO-1006',
      status: 'pickup_scheduled',
      createdAt: '2026-04-28T08:30:00Z',
      studentName: 'David Kim',
      email: 'dkim@buffalo.edu',
      phone: '(716) 555-0106',
      housingType: 'dorm',
      dormName: 'South Lake Village',
      roomNumber: '305',
      floor: 3,
      hasElevator: true,
      boxCount: 4,
      furnitureItems: [],
      cardboardBoxesRequested: 4,
      boxDeliveryDate: '2026-05-07',
      pickupDate: '2026-05-18',
      pickupTimeSlot: '3pm-6pm',
      fallDeliveryDate: '',
      fallDeliveryScheduledLater: true,
      fallDeliveryHousingType: 'dorm',
      hasInsurance: false,
      insurancePhotosSent: false,
      totalPrice: 59.96,
      depositAmount: 12.0,
      depositPaid: true,
      depositPaymentMethod: 'venmo',
      balancePaid: false,
    },
    {
      id: 'UB-STO-1007',
      status: 'delivery_scheduled',
      createdAt: '2026-04-05T13:00:00Z',
      studentName: 'Lisa Thompson',
      email: 'lthompson@buffalo.edu',
      phone: '(716) 555-0107',
      housingType: 'off-campus',
      address: '456 Elmwood Ave, Buffalo, NY 14222',
      floor: 2,
      hasElevator: true,
      boxCount: 15,
      furnitureItems: [
        { type: 'Mini Fridge', price: 69.99, quantity: 1 },
        { type: 'Items Larger than Standard Box', price: 79.99, quantity: 2 },
      ],
      cardboardBoxesRequested: 9,
      boxDeliveryDate: '2026-05-04',
      pickupDate: '2026-05-11',
      pickupTimeSlot: '9am-12pm',
      fallDeliveryDate: '2026-08-27',
      fallDeliveryScheduledLater: false,
      fallDeliveryHousingType: 'off-campus',
      hasInsurance: true,
      insurancePhotosSent: true,
      totalPrice: 253.85,
      depositAmount: 50.77,
      depositPaid: true,
      depositPaymentMethod: 'stripe',
      balancePaid: true,
      balancePaymentMethod: 'stripe',
    },
  ];
}
